// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqnmY2Gi6qf4c6alRJdiPXtkIJDPxSa-g',
    appId: '1:447943279883:web:6e81750d6ba8dc3ae20e0e',
    messagingSenderId: '447943279883',
    projectId: 'turf-c9fc1',
    authDomain: 'turf-c9fc1.firebaseapp.com',
    storageBucket: 'turf-c9fc1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-OWW8jrv1YzUr-5BepzHgA4N1oF9CLqw',
    appId: '1:447943279883:android:616ae8f45a6bbaa7e20e0e',
    messagingSenderId: '447943279883',
    projectId: 'turf-c9fc1',
    storageBucket: 'turf-c9fc1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWeS1Z95pO-XxFkfeVuExV7TXRrBc4SlY',
    appId: '1:447943279883:ios:051fcfeb68b1df2de20e0e',
    messagingSenderId: '447943279883',
    projectId: 'turf-c9fc1',
    storageBucket: 'turf-c9fc1.appspot.com',
    iosClientId: '447943279883-r3dcqfkdkrjorkvkl5n7iu0fiviveg0c.apps.googleusercontent.com',
    iosBundleId: 'com.example.turf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWeS1Z95pO-XxFkfeVuExV7TXRrBc4SlY',
    appId: '1:447943279883:ios:051fcfeb68b1df2de20e0e',
    messagingSenderId: '447943279883',
    projectId: 'turf-c9fc1',
    storageBucket: 'turf-c9fc1.appspot.com',
    iosClientId: '447943279883-r3dcqfkdkrjorkvkl5n7iu0fiviveg0c.apps.googleusercontent.com',
    iosBundleId: 'com.example.turf',
  );
}
